### ISSUE TITLE
Lambda - Node 6.10 EOL April 30th 2019

### ISSUE THREAD

**Issue by blaketastic2** [juiceinc/terraform-aws-juiceinc-waf#2]
Reminder: End of life for Node 6.10 at the end of month.

**Comment by adriennefriend** [comment]
thanks @blaketastic2 !

**Comment by cwire4** [comment]
Thanks for pointing this out @blaketastic2!  We've made a new release, v0.2.1, that updates the runtime defined for the IP updater lambda to nodejs8.10.  In testing it ran as expected with no need to update anything or repackage, and with a bonus speedup.
